name: firebase_stacktrace_decoder

version: 0.1.0

description: A new Flutter project.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.4.0
  bloc_concurrency: ^0.2.1
  desktop_drop: ^0.4.1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  fading_edge_scrollview: ^3.0.0
  file_picker: ^5.2.5
  flutter_bloc: ^8.1.2
  get: ^4.6.5
  hive: ^2.2.3
  intl: ^0.17.0
  list_ext: ^1.0.6
  logging: ^1.1.1
  loader_overlay: ^2.1.0
  meta: ^1.8.0
  multiple_localization: ^0.3.0
  multi_split_view: ^2.4.0
  path: ^1.8.2
  path_provider: ^2.0.11
  pluto_menu_bar: ^3.0.1
  string_ext: ^0.2.0
  tabbed_view: ^1.16.0+1
  toggle_switch: ^2.0.1
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  pubspec_dependency_sorter: ^1.0.3
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
