// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:firebase_stacktrace_decoder/models/core/artifact/artifact.dart';
import 'package:firebase_stacktrace_decoder/models/core/platform/platform.dart';
import 'package:firebase_stacktrace_decoder/models/core/project/project.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArtifactAdapter());
    registerAdapter(PlatformAdapter());
    registerAdapter(PlatformTypeAdapter());
    registerAdapter(ProjectAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArtifactAdapter());
    registerAdapter(PlatformAdapter());
    registerAdapter(PlatformTypeAdapter());
    registerAdapter(ProjectAdapter());
  }
}
